In [2]:
jupyterhub = '/dados/home/joaoviniciuspr'
jupyterlab = '/Users/jjoao/OneDrive/Documentos/Faculdade'
ju = jupyterhub
directory = ju+'/IC_Redes/Trabalhos/UCM/Fase1/Homem_de_Ferro_1'

In [3]:
import pandas as pd
import numpy as np
import sys
sys.path.insert(0,ju+'/IC_Redes/Funcoes')
from ID import ID
from Scene import Scene
from Relation import Relation
from Graph import Graph

In [4]:
hf3=Graph(directory)

In [5]:
hf3.get_shortest_path()

In [6]:
hf3.shortest_path_csv()

In [7]:
hf3.shortest_path

        Distance                  Path
ID
001 001        0                 [001]
001 002        1            [001, 002]
001 003        1            [001, 003]
001 004        1            [001, 004]
001 005        1            [001, 005]
001 006        1            [001, 006]
001 007        1            [001, 007]
001 008        1            [001, 008]
001 009        1            [001, 009]
001 010        1            [001, 010]
001 011        1            [001, 011]
001 012        1            [001, 012]
001 013        1            [001, 013]
001 014        2       [001, 004, 014]
001 015        1            [001, 015]
001 016        1            [001, 016]
001 017        1            [001, 017]
001 018        1            [001, 018]
001 019        1            [001, 019]
001 020        1            [001, 020]
001 021        1            [001, 021]
001 022        1            [001, 022]
001 023        1            [001, 023]
001 024        1            [001, 024]
001 025        1            [001, 025]
001 026        1            [001, 026]
001 027        1            [001, 027]
001 028        1            [001, 028]
001 029        1            [001, 029]
001 030        1            [001, 030]
...          ...                   ...
114 085        3  [114, 001, 009, 085]
114 086        2       [114, 001, 086]
114 087        2       [114, 001, 087]
114 088        2       [114, 001, 088]
114 089        2       [114, 001, 089]
114 090        2       [114, 001, 090]
114 091        2       [114, 001, 091]
114 092        2       [114, 001, 092]
114 093        2       [114, 001, 093]
114 094        2       [114, 001, 094]
114 095        2       [114, 001, 095]
114 096        3  [114, 001, 004, 096]
114 097        3  [114, 001, 004, 097]
114 098        3  [114, 001, 003, 098]
114 099        3  [114, 001, 003, 099]
114 100        3  [114, 001, 003, 100]
114 101        3  [114, 001, 003, 101]
114 102        3  [114, 001, 003, 102]
114 103        2       [114, 001, 103]
114 104        2       [114, 001, 104]
114 105        2       [114, 001, 105]
114 106        2       [114, 001, 106]
114 107        2       [114, 001, 107]
114 108        2       [114, 001, 108]
114 109        2       [114, 001, 109]
114 110        1            [114, 110]
114 111        1            [114, 111]
114 112        1            [114, 112]
114 113        1            [114, 113]
114 114        0                 [114]

[12996 rows x 2 columns]